library(microbiome)
library(biomformat)
library(ape)
p0 <- read_csv2phyloseq(otu.file = "asv.tab.noUnderscores.csv", taxonomy.file="asv.taxonomy.noUnderscores.csv", metadata.file="../../../../Mock.samples.csv", sep=",")
print(otu_table(p0))
print(sample_data(p0))
m0 <- make_biom(data=data.frame(otu_table(p0)), sample_metadata=data.frame(sample_data(p0)), observation_metadata=data.frame(tax_table(p0)))
write_biom(m0, "mystuff.biom")
random_tree = rtree(ntaxa(p0), rooted=TRUE, tip.label=taxa_names(p0))
p1 = merge_phyloseq(p0, random_tree)
write.tree(phy_tree(p1), "mystuff.tre", tree.names=TRUE)
